version: 0.0
os: linux
files:
  - source: build/libs/epic-grepers-0.0.1-SNAPSHOT.jar
    destination: /home/ec2-user/epic-grepers.jar
hooks:
  AfterInstall:
    - location: scripts/after-install.sh
      timeout: 300
      runas: root
