version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      runas: root
      timeout: 300
  AfterInstall:
    - location: scripts/after-install.sh
      runas: root
      timeout: 300
  ApplicationStart:
    - location: scripts/app-start.sh
      runas: root
      timeout: 60
