map: "https://raw.githubusercontent.com/Grepers/epic-grepers/master/src/main/resources/map-office.yml"
actors:
  Greper:
    sightAperture: 2
    sightRadius: 5000
    hearingRadius: 200
    radius: 0.5
    maxVel: 5
    health: 100
    firerate: 3
  Bullet:
    radius: 0.15
    lifespan: 3
    maxVel: 50
    damage: 50
    health: 1
  Wall:
    health: 1000
  Moustache:
    sightAperture: 2
    sightRadius: 5000
    hearingRadius: 200
    radius: 0.5
    maxVel: 5
    health: 100