map: "/map-office.yml"
actors:
  Greper:
    radius: 0.5
    maxVel: 5
    health: 100
    firerate: 3
  Bullet:
    radius: 0.05
    lifespan: 3
    maxVel: 50
    damage: 50
  Wall:
    health: 1000
